 INSERT INTO tb_culinary (photo, name) VALUES
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/italian.png', 'Italiana'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/mexican.png', 'Mexicana'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/indian.png', 'Indiana'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/japan.png', 'Japonesa'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/chinese.png', 'Chinesa'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/french.png', 'Francesa'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/spanish.png', 'Espanhola'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/thai.png', 'Tailandesa'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/grega.png', 'Grega'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/korean.png', 'Coreana'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/vietnam.png', 'Vietnamita'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/turkish.png', 'Turca'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/marroco.png', 'Marroquina'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/peruvian.png', 'Peruana'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/brazilian-food.png', 'Brasileira'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/germany.png', 'Alemã'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/portuguese.png', 'Portuguesa'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/polish.png', 'Polonesa'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/hawaiian.png', 'Havaiana'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/persian.png', 'Persa'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/etiopia.png', 'Etiópica'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/african.png', 'Africana'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/israelense.png', 'Israelense'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/escandinave.png', 'Escandinava'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/colombian.png', 'Colombiana'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/venezuelan.png', 'Venezuelana'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/argentine.png', 'Argentina'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/chilean.png', 'Chilena'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/canadian.png', 'Canadense'),
 ('https://foodway-public-s3.s3.amazonaws.com/website-images/australian.png', 'Australiana');



 INSERT INTO tb_tag (id_tag, name, created_at, updated_at) VALUES
  (1, 'Tem bicicletário', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (2, 'Pet Friendly', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (3, 'Ambiente Infantil', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (4, 'Bebida Alcoólica', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (5, 'Wi-Fi Gratuito', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (6, 'Outdoor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (7, 'Estacionamento', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (9, 'Música ao Vivo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (10, 'Opções Veganas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (11, 'Cartão Fidelidade', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (12, 'Delivery', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (13, '24 Horas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (14, 'Eco-friendly', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (15, 'Estacionamento Pago', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (16, 'Familiar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (17, 'Estacionamento Grátis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (18, 'Aberto Até Tarde', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (19, 'Happy Hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (20, 'Reserva', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (21, 'Eventos Privados', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (22, 'Menu de Brunch', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (23, 'Bar Esportivo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (24, 'Terraço', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);